name: "Trabalho Final CI-CD projeto backend"

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes backend
        run: yarn run test

      - name: Verificar o status dos testes
        run: |
          if [ $? -ne 0 ]; then
            echo "Os testes falharam."
            exit 1
          else
            echo "Todos os testes passaram com sucesso!"
          fi
